services:
  - type: web
    name: landd_app-frontend
    env: node
    buildCommand: npm install --production --no-optional && npm run build
    startCommand: node server.js
    plan: starter
    envVars:
      - key: REACT_APP_API_URL
        value: https://landd-app-backend-docker.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        sync: false
      - key: BASE_PATH
        value: /admin 