name: landd-app
region: sgp  # Change to your preferred region (nyc, sfo, sgp, lon, fra, tor, blr, ams)

services:
  # Backend service with Docker (has Chrome/Puppeteer)
  - name: backend
    github:
      repo: your-username/your-repo-name  # Update with your actual repo
      branch: development
      deploy_on_push: true
    dockerfile_path: ./backend/Dockerfile
    dockerfile_context: ./backend
    http_port: 5000
    instance_count: 1
    instance_size_slug: professional-xs  # Adjust based on your needs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_EXPIRE
        value: 7d
      - key: PORT
        value: "5000"
      - key: FRONTEND_URL
        value: https://app.landd.com.au  # Update with your frontend URL

  # Frontend service (Node.js)
  - name: frontend
    github:
      repo: your-username/your-repo-name  # Update with your actual repo
      branch: development
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    run_command: cd frontend && node server.js
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs  # Adjust based on your needs
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: https://backend-xxxxx.ondigitalocean.app/api  # Update with your backend URL after first deploy
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GOOGLE_MAPS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        value: "3000"

